Tildes y arreglos en el post
OzzzM/hyperblog pull request #1
Opened 2021-04-01 23:47 UTC by OzzzM

No debimos pasar este error a master.

2021-04-01 23:52 UTC, screamox02 requested changes
En vez de usar tildes directas, usa entidades HTML.

2021-04-02 00:07 UTC, screamox02 commented
cambios hechos, por favor hazme el pull request.

2021-04-02 00:08 UTC, OzzzM commented
cambios hechos, por favor hazme el pull request.

2021-04-02 00:09 UTC, screamox02 approved these changes
Excelente, eso era!

2021-04-02 00:10 UTC, merged